# Generated by Django 4.0.1 on 2024-02-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
